package constants;

public enum Emails {

    ORDER_REGISTERED,
    ORDER_CONFIRMED,
    ORDER_CANCELED,
    REPLENISHMENT_REGISTERED,
    REPLENISHMENT_CONFIRMED,
    REPLENISHMENT_CANCELED,
    REGISTRATION,
    RECOVERY,
    NEW_PASSWORD,
    TICKET,
    MESSAGE,
    NEWSLETTER,
    FEEDBACK;
}
